### ISSUE TITLE
applesimutils binary has not been found in your PATH

### ISSUE THREAD

**Issue by olezvinskyi** [wix/AppleSimulatorUtils#101]
**Description**
When I am trying to run Appium tests which are setting capabilities 
`options.setPermissions(new Permissions("{\""+config().bundleIdIos()+"\": {\"userTracking\": \"NO\", \"location\": \"always\", \"notifications\": \"NO\"}}"));`

I got next exception 

[debug] [BaseDriver] Event 'newSessionStarted' logged at 1658477212836 (01:06:52 GMT-0700 (Pacific Daylight Time))
[debug] [W3C] Encountered internal error running command: Error: applesimutils binary has not been found in your PATH. Please install it ('brew tap wix/brew && brew install wix/brew/applesimutils') to be able to change application permissions
[debug] [W3C]     at execWix (/usr/local/lib/node_modules/appium/node_modules/appium-ios-simulator/lib/permissions.js:41:11)
[debug] [W3C]     at Permissions.setAccess (/usr/local/lib/node_modules/appium/node_modules/appium-ios-simulator/lib/permissions.js:75:12)
[debug] [W3C]     at SimulatorXcode11_4.setPermissions (/usr/local/lib/node_modules/appium/node_modules/appium-ios-simulator/lib/simulator-xcode-6.js:1358:5)
[debug] [W3C]     at SimulatorXcode11_4.setPermissions (/usr/local/lib/node_modules/appium/node_modules/appium-ios-simulator/lib/simulator-xcode-11.4.js:93:12)
[debug] [W3C]     at XCUITestDriver.start (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:492:11)
[debug] [W3C]     at XCUITestDriver.createSession (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:256:7)
[debug] [W3C]     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:387:35)
[HTTP] <-- POST /wd/hub/session 500 4464 ms - 851

**Environment**
 - macOS version: 12.4
 - Xcode version: 13.4.1
 - Appium 1.23.0-beta.0
 - java 15
 - applesimutils latest version

**Comment by olezvinskyi** [comment]
not an issue
