### ISSUE TITLE
Handle booting devices better when attempting to set a notification permission

### ISSUE THREAD

**Issue by Crash--** [wix/AppleSimulatorUtils#22]
#### Description
Sometimes, on a CI service, detox / AppleSimulatorUtils is a bit flaky, and I had 
`Error: BulletinBoard property list not found.` (on bitrise). It seems that this error has already been reported on detox repo https://github.com/wix/detox/issues/452#issuecomment-350646303 and https://github.com/wix/detox/issues/452#issuecomment-355123878 

With the help of some screenshots, it appears that this error tell us that the simulator / app is not ready yet, when we try to launch the app.

In fact, it seems that detox timeout / resolves await device.launchApp even if the simulator is not up & ready.

Also, I think it's worth to mention, but before I used to run : 
```js 
await detox.init(config, {launchApp: true});
//and is my test something like 
await device.launchApp({
       permissions: { notifications: 'YES', calendar: 'YES' }
});
```
but in this case I generaly got the native iOS modale requesting if I accept or not the notification. But no timeout error. So I change to not launch the app on init() and it now seems to work correctly (after a few hours in production, no fail yet).

I don't know how I can change the default timeout for detox.launchApp(), but after a few tests, here is my current workaround is to try/catch the launchApp() and relaunchApp() after a long sleep.

#### Steps to Reproduce
```js
before(async () => {
  await detox.init(config, { launchApp: false });
   try {
     await device.launchApp({ permissions: { notifications: 'YES', calendar: 'YES' } });
   } catch (e) {
     console.log('It will certainly throw an exception, but lets sleep for 60000ms', e);
     await sleep(60000);
     await device.launchApp({ permissions: { notifications: 'YES', calendar: 'YES' } });
     console.log('hey, sleep is over. Crossed fingers');
  }
})
after(async () => {
    await deviceUtils.takeScreenshot('after_test');		    
    await detox.cleanup();
  })
```

Output : 
```
(node:8531) DeprecationWarning: "--compilers" will be removed in a future version of Mocha; see https://git.io/vdcSr for more info
detox-server info 11:15:20: server listening on localhost:49353...
detox info 1: Searching for device matching iPhone 7... 
detox info 5: Booting device 9CB16873-88A3-4D3C-AC24-67C27AC818B3 
detox info 7: Uninstalling io.getknow... 
detox info 7: io.getknow uninstalled 
detox info 8: Installing /Users/vagrant/git/ios/build/Build/Products/Release-iphonesimulator/getknow.app... 
detox info 8: /Users/vagrant/git/ios/build/Build/Products/Release-iphonesimulator/getknow.app installed 
detox info 9: Trying to set permissions... 
It will certainly throw an exception, but lets sleep for 60000ms { ChildProcessError: Command failed: applesimutils --simulator 9CB16873-88A3-4D3C-AC24-67C27AC818B3 --bundle io.getknow --setPermissions notifications=YES,calendar=YES
Error: BulletinBoard property list not found.

 `applesimutils --simulator 9CB16873-88A3-4D3C-AC24-67C27AC818B3 --bundle io.getknow --setPermissions notifications=YES,calendar=YES` (exited with error code 253)
    at callback (/Users/vagrant/git/node_modules/child-process-promise/lib/index.js:33:27)
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  name: 'ChildProcessError',
  code: 253,
  childProcess: 
   { ChildProcess: { [Function: ChildProcess] super_: [Object] },
     fork: [Function],
     _forkChild: [Function],
     exec: [Function],
     execFile: [Function],
     spawn: [Function],
     spawnSync: [Function: spawnSync],
     execFileSync: [Function: execFileSync],
     execSync: [Function: execSync] },
  stdout: 'A collection of utils for Apple simulators.\n\nUsage:\n    applesimutils --byId <simulator identifier> --bundle <bundle identifier> --setPermissions "<permission1>, <permission2>, ..."\n    applesimutils --byName <simulator name> --byOS <simulator OS version> --bundle <bundle identifier> --setPermissions "<permission1>, <permission2>, ..."\n    applesimutils --simulator <simulator name/identifier> --restartSB\n    applesimutils --list [--byName <simulator name>] [--byOS <simulator OS version>] [--byType <simulator OS version>] [--maxResults <int>]\n\nOptions:\n    --byId             Filters simulators by identifier\n    --byName           Filters simulators by name\n    --byType           Filters simulators by device type\n    --byOS             Filters simulators by operating system\n    --list             Lists available simulators\n    --setPermissions   Sets the specified permissions and restarts SpringBoard for the changes to take effect\n    --clearKeychain    Clears the simulator\'s keychain\n    --restartSB        Restarts SpringBoard\n    --bundle           The app bundle identifier\n    --maxResults       Limits the number of results returned from --list\n    --version, -v      Prints version\n    --help, -h         Prints usage\n\nAvailable Permissions:\n    calendar=YES|NO|unset\n    camera=YES|NO|unset\n    contacts=YES|NO|unset\n    health=YES|NO|unset\n    homekit=YES|NO|unset\n    location=always|inuse|never|unset\n    medialibrary=YES|NO|unset\n    microphone=YES|NO|unset\n    motion=YES|NO|unset\n    notifications=YES|NO|unset\n    photos=YES|NO|unset\n    reminders=YES|NO|unset\n    siri=YES|NO|unset\n    speech=YES|NO|unset\n\n\nFor more features, open an issue at https://github.com/wix/AppleSimulatorUtils\nPull-requests are always welcome!\n',
  stderr: 'Error: BulletinBoard property list not found.\n\n' }
detox info 10: Trying to set permissions... 
detox info 10: Permissions are set 
detox info 11: Launching io.getknow... 
detox info 11: io.getknow launched. The stdout and stderr logs were recreated, you can watch them with:
        tail -F $HOME/Library/Developer/CoreSimulator/Devices/9CB16873-88A3-4D3C-AC24-67C27AC818B3/data/tmp/detox.last_launch_app_log.{out,err} 
hey, sleep is over. Crossed fingers
  Login
   • 📸  init.png
    ✓ should have login button (3746ms)
    ✓ should show connexion screen after tap (607ms)
    ✓ should show home screen after login (11239ms)
```
#### Device, macOS and Xcode Versions
 macOS : 10.12 (Sierra)
* Xcode Version:
Xcode 9.2
Build version 9C40b

**Comment by LeoNatan** [comment]
Running AppleSimUtils alone, I am unable to reproduce for new (never booted) or old (booted at least once) simulators. So I think this is a Detox issue after all. I think it's due to Detox booting the simulator first, then calling `--setPermissions`. @rotemmiz

**Comment by LeoNatan** [comment]
@Crash-- Could you please try running the `applesimutils` command on your Mac outside of Detox? Just to test. Create a new simulator in Xcode, do not boot it, and run `applesimutils` in the same manner as Detox does, passing the correct simulator id. See if that throws the same error or succeeds.

**Comment by LeoNatan** [comment]
@Crash-- Could you please upgrade by using `brew upgrade applesimutils` and see if it works better now?

**Comment by Crash--** [comment]
Since 4h, all my builds are now failing...

It seems that : 
- Now i don't need to retry the launch of the simulator (since my catch is not triggered anymore) 
- But... permissions are not set even if the logs tell me so. 
```
detox info 8: Installing /Users/vagrant/git/ios/build/Build/Products/Release-iphonesimulator/getknow.app... 
detox info 8: /Users/vagrant/git/ios/build/Build/Products/Release-iphonesimulator/getknow.app installed 
detox info 9: Trying to set permissions... 
detox info 9: Permissions are set 
detox info 10: Launching io.getknow... 
```

![after_test](https://user-images.githubusercontent.com/1107936/34825085-6341d40c-f6d1-11e7-9412-b00975c14963.png)

**Comment by LeoNatan** [comment]
Oh no
I will continue looking.

**Comment by LeoNatan** [comment]
I am unable to reproduce…

**Comment by LeoNatan** [comment]
@Crash-- Could you run your Detox using verbose output? I am interested to see what it says.

**Comment by LeoNatan** [comment]
I tested both first-time and previously-booted devices, and both cases work.

**Comment by Crash--** [comment]
I just downgraded to 0.5.19 and my workaround still works. 

I'm currently talking with bitrise to see if I can get an access to share here in order to debug. It's such a pain to test and break my current CI pipeline. 

Will come back to you with verbose log soon

**Comment by LeoNatan** [comment]
Hey,
Any news on this issue? I am unable to reproduce.
